# Proxy DHCP (consigliato)
no-dhcp-interface=lo
dhcp-range=192.168.1.0,proxy

# TFTP
enable-tftp
tftp-root=/pxe

# Boot file
# Sostituisci 192.168.1.XX con l'IP reale del tuo host
dhcp-boot=boot/vmlinuz-lts,,192.168.1.XX

# Log utili
log-dhcp
log-facility=-
