services:
  pxe-dnsmasq:
    build:
      context: dnsmasq
      args:
        ALPINE_BASE_VERSION: ${ALPINE_BASE_VERSION}
    container_name: pxe-dnsmasq
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    volumes:
      - alpine-netboot:/pxe
  pxe-httpd:
    build:
      context: httpd
      args:
        ALPINE_BASE_VERSION: ${ALPINE_BASE_VERSION}
    container_name: pxe-httpd
    restart: unless-stopped
    network_mode: host
    volumes:
      - alpine-netboot:/pxe:ro
  pxe-ansible:
    build:
      context: alpine
    container_name: pxe-alpine
    network_mode: host
volumes:
  alpine-netboot:
